name: firstAction
on: push  
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: main
      
      - name: Install Node Js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.18.0

      - name: First Action Try
        run: echo "Hello"
 
      - name: Show Node Version
        run: node -v
      
      - name: Install All Packages
        run: npm ci
        

                
            
