name: Second Action
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
    newJob:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout to the repo
              uses: actions/checkout@v4.2.2
              with:
                ref: main
            
            - name: Install Node Js 20.18.0
              uses: actions/setup-node@v4.1.0

            - name: Printing on console
              run: echo "Second Action"

            - name: Check Node Version
              run: node -v
    
    newJob1:
        runs-on: ubuntu-22.04
        permissions:
          actions: write
          attestations: read
          checks: read
          contents: write
  
        
        steps:
            - name: Checkout to the repo
              uses: actions/checkout@v4.2.2
              with:
                ref: main
            
            - name: Install Node Js 20.18.0
              uses: actions/setup-node@v4.1.0

            - name: Printing on console
              run: echo "Second Action"

            - name: Check Node Version
              run: node -v

            - id: 'generate-secret'
              shell: bash
              run: echo "HHHHHH"
            
            - id: set-date
              name: should Return Date
              shell: bash
            #  run: echo "currentDate=$(date +'%Y-%m-%d')" 
              run: echo "currentDate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
            
            - name: Check Output
              run: echo ${{steps.set-date.outputs.currentDate}}

            - name: Create a New Checkpoint Branch
              run: |
                git pull origin main
                git checkout -b best-known-good-version-${{steps.set-date.outputs.currentDate}}
                git push origin best-known-good-version-${{steps.set-date.outputs.currentDate}}
                git checkout -
